version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  lint:
    executor:
      name: node/default
    steps: 
      - node/with-cache:
        steps:
          - run: nx affected:lint
workflows:
    buildster:
      jobs:
        - install
        - lint