version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  lint:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: nx affected:lint
  test:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: nx affected:test
  build:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: nx affected:build
  integration:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: nx affected:e2e
workflows:
    buildster:
      jobs:
        - install
        - lint:
          -requires:
            - install
        - test:
          -requires:
            - install
        - build:
          -requires:
            - install
        - integration:
          -requires:
            - install

