version: 2.1
jobs:
  install:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/workspace
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: codebase-{{ .BuildNum }}
          paths:
            - ~/workspace
  lint:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/workspace
    steps:
      - restore_cache:
          key: codebase-{{ .BuildNum }}
      - run: echo lint
      - run: ~/workspace/node_modules/.bin/nx affected:lint
  build:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/workspace
    steps:
      - restore_cache:
          key: codebase-{{ .BuildNum }}
      - run: ~/workspace/node_modules/.bin/nx affected:build
  test:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/workspace
    steps:
      - restore_cache:
          key: codebase-{{ .BuildNum }}
      - run: ~/workspace/node_modules/.bin/nx affected:test
  e2e:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/workspace
    steps:
      - restore_cache:
          key: codebase-{{ .BuildNum }}
      - run: ~/workspace/node_modules/.bin/nx affected:e2e
  dockerize:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/workspace
    steps:
      - run: echo dockerize
  publish:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/workspace
    steps:
      - run: echo publish
  tag:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/workspace
    steps:
      - run: echo tag
  reports:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/workspace
    steps:
      - run: echo reports
workflows:
  version: 2
  buildster:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - e2e:
          requires:
            - install
      - dockerize:
          requires:
            - lint
            - build
            - test
            - e2e
      - publish:
          requires:
            - lint
            - build
            - test
            - e2e
      - tag:
          requires:
            - dockerize
            - publish
      - reports:
          requires:
            - test
            - e2e